In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
import numpy as np
A=np.array([
    [2,-1],
    [0,3]
])
B=np.array([
    [1,2],
    [-3,4]
])
alpha=3
beta=2
print("A+B:")
print(A+B)
print("A*B:")
print(A*B)
print("3A-2B:")
print(alpha*A-beta*B)

A+B:
[[ 3  1]
 [-3  7]]
A*B:
[[ 2 -2]
 [ 0 12]]
3A-2B:
[[ 4 -7]
 [ 6  1]]


In [3]:
#determinant
det_val = np.linalg.det(A)
print("Determinant:", det_val)

Determinant: 6.0


In [ ]:
#inverse of matrix
A_inv = np.linalg.inv(A)

print("Inverse of A:")
print(A_inv)

Inverse of A:
[[0.5        0.16666667]
 [0.         0.33333333]]


In [ ]:
#eigenvalues and eigenvectors
C=np.array([
    [4,1],
    [-2,1]
])

eigenvalues, eigenvectors = np.linalg.eig(C)

print("Matrix C:")
print(C)
print("Eigenvalue (first):")
print(eigenvalues[0])
print("Corresponding Eigenvector:")
print(eigenvectors[:, 0])

Matrix C:
[[ 4  1]
 [-2  1]]
Eigenvalue (first):
3.0
Corresponding Eigenvector:
[ 0.70710678 -0.70710678]


In [23]:
# Feature matrix
X=np.array([
    [4,1.5,100], #car 1
    [6,2.0,150]  #car 2
])

# Price vector
y=np.array([20,30])

#X.T*B=y
#B=(X.T*X)^-1 X^T y
#X.T is transpose matrix
beta=np.linalg.pinv(X.T @ X) @ X.T @ y #coefficients

# Features of car 3
car3=np.array([8, 3.0, 200])

# Predicted price of car 3
price_car3=car3 @ beta
print("Predicted price:",price_car3)


Predicted price: 39.99999999999998
